### PR TITLE
Change to the regex generation when character ord matches 65

### PR DESCRIPTION
**Pull request by r3hp1c**
While using Javascript::Packer on a large project that substitutes data into JavaScript I found that in some cases we were getting the "Invalid or unexpected token" error message for the minified JavaScript in the browser.

After investigation I found that the regular expression generated for the browser to un-minify was

e=function(){return'([wyEHKLQW-Z]|[0-9a][0-9a-zA-Z])'}

this caused that not all place holders were correctly replaced back due to this section **]|[0-9a][**

Expect that the regular expression should be

e=function(){return'([wyEHKLQW-Z]|[0-9a-zA][0-9a-zA-Z])'}

Please review pull request that fixes the issue.

### CODE REVIEW

**Comment by leejo** [comment]
🤔 seems ok - is the character class correct here: `[0-9a-zA]` - do we not need also `-Z` on that so we have `[0-9a-zA-Z]`?

**Comment by r3hp1c** [comment]
Doing some additional testing to validate.

**Comment by r3hp1c** [comment]
Yes, [0-9a-zA] works as expected.  When we hit ord 66 the expression is made [0-9a-zA-B] already and there is a specific check for generating the expression when the character is Z which makes the expression something like 1[0-9a-zA-Z]{2}|[0-9a-zA-Z]{2}

**Comment by leejo** [comment]
OK sounds good! Thanks for the contribution - I'll get this merged and release to CPAN in the next day or two.

**Pull request merged**
